spring:
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max_active: 16
        max_wait: 3000
    password: root
    pool:
      max_active: 16
      max_wait: 3000
    # sentinel:
    #   master: sentinel-127.0.0.1
    #   nodes: 127.0.0.1
    timeout: 6000