spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pedestal?autoRconnect=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 30
      min-idle: 10
      max-wait: 800
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      validation-query: SELECT 'x'
      validation-query-timeout: 2500
      pool-prepared-statements: true
      connection-properties: config.decrypt=true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      stat-view-servlet:
        enabled: true
        stat-view-servlet.url-pattern: /druid/*
        stat-view-servlet.login-username: admin
        stat-view-servlet.login-password: admin

# mybatis
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.dumas.pedestal.*.entity
    # type-handlers-package: com.dumas.pedestal.common.handler
    global-config:
        #数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            logic-delete-value: -1
            logic-not-delete-value: 0
        banner: false
    #原生配置
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'